//
//  CAPMain.swift
//  medlearn
//
//  Created by Michael Albrecht on 8/5/20.
//  Copyright © 2020 Michael Albrecht. All rights reserved.
//

import SwiftUI



struct CAPMain: View {
    
    @State private var siteSelection: Int = 0
    @State private var site: String? = nil
    
    
    let siteOfTreatment = ["Inpatient", "Outpatient"]
    
    private let fillColor = Color.pink

    
    var body: some View {
        
        
            ZStack {
                Color(.gray).opacity(0.1).edgesIgnoringSafeArea(.all)
                
                VStack(spacing: 30) {
                    Text("Community Acquired Pneumonia")
                        .modifier(MyTitleModifier(fillColor: fillColor))
                        
                    
                    ShowPicker(parentBinding: $siteSelection, text: "Select site of treatment", parentArray: siteOfTreatment)
                    
                    
                    Text("Note: The PSI or CURB-65 scores can be generated by other apps or online calculators to help decide on a site of treatment (PSI is preferred). \n\nAlso please note that the treatment of aspiration pneumonia no longer differs from other forms of community-acquired pneumonia.  However, anerobic coverage can be added if empyema or lung abscess is suspected.")
                    .padding()
                    .lineLimit(10)
                    .minimumScaleFactor(0.5)
                    
                    NavigationLink(destination: InpatientCAP(), tag: "inpatient", selection: $site) {
                        EmptyView()
                    }.isDetailLink(false)
                    NavigationLink(destination: OutpatientCAP(), tag: "outpatient", selection: $site) {
                        EmptyView()
                    }.isDetailLink(false)
                    Button("Next") {
                        if self.siteSelection == 0 {
                            self.site = "inpatient"
                        } else if self.siteSelection == 1 {
                            self.site = "outpatient"
                        }
                    }.buttonStyle(GradientButtonStyle(fillColor: fillColor))
                    Spacer()
                }
                
                
                
            }
       
        
    }
}

struct CAPMain_Previews: PreviewProvider {
    static var previews: some View {
        CAPMain()
    }
}
